apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-bucket
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/storage-bucket
    type: DirectoryOrCreate
